#ifndef PLATFORM_GENERIC_H_
#define PLATFORM_GENERIC_H_

#include <stdint.h>

namespace Platform
{
    // TODO: Find some clever high-level fusion/MPL way of defining the columns and rows such that we don't
    //       need to hardcode the max number of rows here, but rather have it generated by the compiler just
    //       based on an arbitrary number of column definitions...  even if it means splitting out the input
    //       stuff away from Platform.

    struct InputValuesType
    {
        uint8_t row[6];
    };

    void ReadInputs(InputValuesType& o_inputs);

    unsigned long GetMsec();

    // The following templates need to be specialized for your platform!
    template<uint8_t c>
    struct SetColumn
    {
        void operator() ()
        {
        }
    };

    template<uint8_t c>
    struct ResetColumn
    {
        void operator() ()
        {
        }
    };

}

#endif
