set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

set(TEENSYDUINO_LIB_PATH      $ENV{ARDUINOPATH}/hardware/teensy/avr/cores/teensy3)
#set(TEENSYDUINO_COMPILER_PATH $ENV{ARDUINOPATH}/hardware/tools/arm/bin)
set(TEENSYDUINO_COMPILER_PATH D:/gcc-arm-none-eabi-7-2017-q4-major-win32/bin)

set(CMAKE_C_COMPILER   ${TEENSYDUINO_COMPILER_PATH}/arm-none-eabi-gcc.exe)
set(CMAKE_ASM_COMPILER ${TEENSYDUINO_COMPILER_PATH}/arm-none-eabi-gcc.exe)
set(CMAKE_CXX_COMPILER ${TEENSYDUINO_COMPILER_PATH}/arm-none-eabi-g++.exe)
set(CMAKE_OBJCOPY      ${TEENSYDUINO_COMPILER_PATH}/arm-none-eabi-objcopy.exe)
set(CMAKE_SIZE         ${TEENSYDUINO_COMPILER_PATH}/arm-none-eabi-size.exe)

set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nosys.specs" CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
